# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1879, 1000)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(801, 547))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settingsFrame = QtWidgets.QFrame(self.centralwidget)
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.settingsFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.settingsGroupBox = QtWidgets.QGroupBox(self.settingsFrame)
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settingsGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.distanceLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.distanceLabel.setObjectName("distanceLabel")
        self.gridLayout_6.addWidget(self.distanceLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 2, 0, 1, 1)
        self.distanceComboBox = QtWidgets.QComboBox(self.settingsGroupBox)
        self.distanceComboBox.setObjectName("distanceComboBox")
        self.gridLayout_6.addWidget(self.distanceComboBox, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.settingsGroupBox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.settingsFrame, 0, 2, 3, 1)
        self.similarFrame = QtWidgets.QFrame(self.centralwidget)
        self.similarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.similarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.similarFrame.setObjectName("similarFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.similarFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.similarGroupBox = QtWidgets.QGroupBox(self.similarFrame)
        self.similarGroupBox.setObjectName("similarGroupBox")
        self.similarTableView = QtWidgets.QTableView(self.similarGroupBox)
        self.similarTableView.setGeometry(QtCore.QRect(0, 20, 611, 271))
        self.similarTableView.setObjectName("similarTableView")
        self.gridLayout_3.addWidget(self.similarGroupBox, 0, 1, 1, 1)
        self.programGroupBox = QtWidgets.QGroupBox(self.similarFrame)
        self.programGroupBox.setObjectName("programGroupBox")
        self.programPlainTextEdit = QtWidgets.QPlainTextEdit(self.programGroupBox)
        self.programPlainTextEdit.setGeometry(QtCore.QRect(0, 20, 611, 271))
        self.programPlainTextEdit.setReadOnly(True)
        self.programPlainTextEdit.setObjectName("programPlainTextEdit")
        self.gridLayout_3.addWidget(self.programGroupBox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.similarFrame, 2, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.themeComboBox = QtWidgets.QComboBox(self.frame)
        self.themeComboBox.setObjectName("themeComboBox")
        self.gridLayout_5.addWidget(self.themeComboBox, 0, 0, 1, 1)
        self.tasksGroupBox = QtWidgets.QGroupBox(self.frame)
        self.tasksGroupBox.setObjectName("tasksGroupBox")
        self.tasksTableView = QtWidgets.QTableView(self.tasksGroupBox)
        self.tasksTableView.setGeometry(QtCore.QRect(0, 20, 601, 261))
        self.tasksTableView.setObjectName("tasksTableView")
        self.gridLayout_5.addWidget(self.tasksGroupBox, 2, 0, 1, 1)
        self.studentsGroupBox = QtWidgets.QGroupBox(self.frame)
        self.studentsGroupBox.setObjectName("studentsGroupBox")
        self.studentsTableView = QtWidgets.QTableView(self.studentsGroupBox)
        self.studentsTableView.setGeometry(QtCore.QRect(0, 20, 601, 251))
        self.studentsTableView.setObjectName("studentsTableView")
        self.gridLayout_5.addWidget(self.studentsGroupBox, 1, 0, 1, 1)
        self.clusterWidget = QtWidgets.QWidget(self.frame)
        self.clusterWidget.setObjectName("clusterWidget")
        self.gridLayout_5.addWidget(self.clusterWidget, 0, 1, 3, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1879, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Настройки"))
        self.distanceLabel.setText(_translate("MainWindow", "Расстояние"))
        self.similarGroupBox.setTitle(_translate("MainWindow", "Похожие студенты"))
        self.programGroupBox.setTitle(_translate("MainWindow", "Текст программы"))
        self.tasksGroupBox.setTitle(_translate("MainWindow", "Задания"))
        self.studentsGroupBox.setTitle(_translate("MainWindow", "Студенты"))
        self.action.setText(_translate("MainWindow", "Открыть"))

