# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1640, 772)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(801, 547))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.settingsFrame = QtWidgets.QFrame(self.centralwidget)
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settingsFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.settingsGroupBox = QtWidgets.QGroupBox(self.settingsFrame)
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settingsGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.forLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.forLabel.setObjectName("forLabel")
        self.gridLayout_6.addWidget(self.forLabel, 5, 0, 1, 1)
        self.repeatLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.repeatLabel.setObjectName("repeatLabel")
        self.gridLayout_6.addWidget(self.repeatLabel, 9, 0, 1, 1)
        self.whileLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.whileLineEdit.setReadOnly(True)
        self.whileLineEdit.setObjectName("whileLineEdit")
        self.gridLayout_6.addWidget(self.whileLineEdit, 7, 1, 1, 1)
        self.forLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.forLineEdit.setReadOnly(True)
        self.forLineEdit.setObjectName("forLineEdit")
        self.gridLayout_6.addWidget(self.forLineEdit, 5, 1, 1, 1)
        self.LoopLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.LoopLabel.setObjectName("LoopLabel")
        self.gridLayout_6.addWidget(self.LoopLabel, 3, 0, 1, 1)
        self.whileLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.whileLabel.setObjectName("whileLabel")
        self.gridLayout_6.addWidget(self.whileLabel, 7, 0, 1, 1)
        self.distanceLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.distanceLabel.setObjectName("distanceLabel")
        self.gridLayout_6.addWidget(self.distanceLabel, 0, 0, 1, 1)
        self.distanceComboBox = QtWidgets.QComboBox(self.settingsGroupBox)
        self.distanceComboBox.setObjectName("distanceComboBox")
        self.gridLayout_6.addWidget(self.distanceComboBox, 1, 0, 1, 2)
        self.repeatLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.repeatLineEdit.setReadOnly(True)
        self.repeatLineEdit.setObjectName("repeatLineEdit")
        self.gridLayout_6.addWidget(self.repeatLineEdit, 9, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.settingsGroupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.settingsGroupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.settingsFrame, 1, 2, 1, 1)
        self.similarFrame = QtWidgets.QFrame(self.centralwidget)
        self.similarFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.similarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.similarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.similarFrame.setObjectName("similarFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.similarFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.similarGroupBox = QtWidgets.QGroupBox(self.similarFrame)
        self.similarGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.similarGroupBox.setObjectName("similarGroupBox")
        self.similarTableView = QtWidgets.QTableView(self.similarGroupBox)
        self.similarTableView.setGeometry(QtCore.QRect(0, 20, 241, 271))
        self.similarTableView.setObjectName("similarTableView")
        self.gridLayout_3.addWidget(self.similarGroupBox, 0, 1, 1, 1)
        self.programGroupBox = QtWidgets.QGroupBox(self.similarFrame)
        self.programGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.programGroupBox.setObjectName("programGroupBox")
        self.programPlainTextEdit = QtWidgets.QPlainTextEdit(self.programGroupBox)
        self.programPlainTextEdit.setGeometry(QtCore.QRect(0, 20, 241, 271))
        self.programPlainTextEdit.setReadOnly(True)
        self.programPlainTextEdit.setObjectName("programPlainTextEdit")
        self.gridLayout_3.addWidget(self.programGroupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.similarFrame, 1, 0, 1, 2)
        self.clusterWidget = QtWidgets.QWidget(self.centralwidget)
        self.clusterWidget.setMinimumSize(QtCore.QSize(500, 400))
        self.clusterWidget.setObjectName("clusterWidget")
        self.gridLayout.addWidget(self.clusterWidget, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.themeLabel = QtWidgets.QLabel(self.frame)
        self.themeLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.themeLabel.setObjectName("themeLabel")
        self.gridLayout_4.addWidget(self.themeLabel, 0, 0, 1, 1)
        self.themeComboBox = QtWidgets.QComboBox(self.frame)
        self.themeComboBox.setObjectName("themeComboBox")
        self.gridLayout_4.addWidget(self.themeComboBox, 0, 1, 1, 1)
        self.tasksGroupBox = QtWidgets.QGroupBox(self.frame)
        self.tasksGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.tasksGroupBox.setObjectName("tasksGroupBox")
        self.tasksTableView = QtWidgets.QTableView(self.tasksGroupBox)
        self.tasksTableView.setGeometry(QtCore.QRect(-3, 23, 241, 331))
        self.tasksTableView.setMinimumSize(QtCore.QSize(0, 0))
        self.tasksTableView.setObjectName("tasksTableView")
        self.gridLayout_4.addWidget(self.tasksGroupBox, 1, 1, 2, 1)
        self.studentsGroupBox = QtWidgets.QGroupBox(self.frame)
        self.studentsGroupBox.setEnabled(True)
        self.studentsGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.studentsGroupBox.setObjectName("studentsGroupBox")
        self.studentsTableView = QtWidgets.QTableView(self.studentsGroupBox)
        self.studentsTableView.setGeometry(QtCore.QRect(-3, 22, 241, 331))
        self.studentsTableView.setMinimumSize(QtCore.QSize(0, 0))
        self.studentsTableView.setObjectName("studentsTableView")
        self.gridLayout_4.addWidget(self.studentsGroupBox, 1, 0, 2, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Настройки"))
        self.forLabel.setText(_translate("MainWindow", "For Loop"))
        self.repeatLabel.setText(_translate("MainWindow", "Repeat Loop"))
        self.LoopLabel.setText(_translate("MainWindow", "Использование циклов в программе"))
        self.whileLabel.setText(_translate("MainWindow", "While Loop"))
        self.distanceLabel.setText(_translate("MainWindow", "Расстояние"))
        self.similarGroupBox.setTitle(_translate("MainWindow", "Похожие студенты"))
        self.programGroupBox.setTitle(_translate("MainWindow", "Текст программы"))
        self.themeLabel.setText(_translate("MainWindow", "Тема"))
        self.tasksGroupBox.setTitle(_translate("MainWindow", "Задания"))
        self.studentsGroupBox.setTitle(_translate("MainWindow", "Студенты"))
        self.action.setText(_translate("MainWindow", "Открыть"))

